Repository dragonchain/dragonchain, pull requests merged in 2019-11, with the labels that each got.

#259 Add getting started links/update dependencies
  CHANGELOG.md
  README.md
  helm/dragonchain-k8s/README.md
  helm/dragonchain-k8s/values.yaml
  requirements.txt
Labels: documentation

#260 Update gunicorn
  CHANGELOG.md
  Dockerfile
  cicd/Dockerfile.dependencies
  cicd/Dockerfile.test
  requirements.txt
Labels: Webserver

#255 Fixes issue where claims aren't being sent to matchmaking.
  CHANGELOG.md
  dragonchain/exceptions.py
  dragonchain/lib/broadcast.py
  dragonchain/lib/matchmaking.py
  dragonchain/transaction_processor/level_1_actions.py
  dragonchain/transaction_processor/level_5_actions.py
  dragonchain/transaction_processor/level_5_actions_utest.py
Labels: L5, Transaction Processor
